"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ListaDuplamenteLigada_1 = require("./ListaDuplamenteLigada");
var Trajeto_1 = require("./Trajeto");
var listaTeste = new ListaDuplamenteLigada_1.ListaDuplamenteLigada;
var trajeto1 = new Trajeto_1.Trajeto("Local 1", 30, 20);
var trajeto2 = new Trajeto_1.Trajeto("Local 2", 10, 15);
var trajeto3 = new Trajeto_1.Trajeto("Local 3", 40, 25);
var trajeto4 = new Trajeto_1.Trajeto("Local 4", 50, 60);
var trajeto5 = new Trajeto_1.Trajeto("Local 5", 15, 20);
listaTeste.adicionar(trajeto1);
listaTeste.adicionar(trajeto2);
listaTeste.adicionar(trajeto3);
listaTeste.adicionar(trajeto4);
listaTeste.adicionar(trajeto5);
console.log("Lista Atual: ", listaTeste.toString());
console.log("Quantidade de elementos na lista: ", listaTeste.tamanho());
listaTeste.remove(3);
console.log("Lista atualizada: ", listaTeste.toString());
listaTeste.removeDoComeco();
console.log("Lista atualizada: ", listaTeste.toString());
listaTeste.removeDoFim();
console.log("Lista atualizada: ", listaTeste.toString());
console.log("A lista contem o trajeto 3? ", listaTeste.contem(trajeto3));
